[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.15.2"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "18.18.0"
  RUBY_VERSION = "2.6.2"
  NODE_OPTIONS = "--max_old_space_size=4096"